#!/usr/bin/env python3
"""Every target must be able to reach '+++' with its own gold answer,
otherwise the teacher loops on it forever: '+' is a soft positive that
resets the failure counter without advancing the success counter."""
import glob, json, re, sys, os
bad=0
# The levels come from disk, not from a range. A hardcoded upper bound silently
# skips the levels most in need of checking -- it read range(0,13) while the
# autonomy loop was writing level 13, so the one config being generated by a
# machine instead of a human was the one nobody validated.
def levels_on_disk(lang='it'):
    out=[]
    for d in glob.glob(f'training_files/{lang}/*'):
        name=os.path.basename(d)
        if name.isdigit() and os.path.exists(f'{d}/local_teacher.json'):
            out.append(int(name))
    return sorted(out)

LEVELS = ([int(a) for a in sys.argv[1:] if a.isdigit()] or levels_on_disk())
for L in LEVELS:
    p=f'training_files/it/{L}/local_teacher.json'
    if not os.path.exists(p): continue
    cfg=json.load(open(p))
    stop=cfg.get('evaluation',{}).get('has_terminator_pattern','[.!?]')
    for sname,s in cfg.get('steps',{}).items():
        req={k:s.get(f'require_{k}',False) for k in ('article','verb','adjective')}
        mw=s.get('max_response_words',6)
        for t in s['targets']:
            if not isinstance(t,dict):
                continue
            r=t.get('expected','')
            noun=t.get('noun',''); art=t.get('article',''); vb=t.get('verb',''); adj=t.get('adjective',''); obj=t.get('object','')
            comp=re.sub(r'\s+','',r)
            def has(w): return True if not w else (bool(re.search(r'\b'+re.escape(w)+r'\b',r)) or (len(w)>=4 and w in comp))
            probs=[]
            if not has(noun): probs.append(f"noun {noun!r} assente")
            if req['article'] and not (art and art in r.split()[:5]): probs.append(f"article {art!r} richiesto ma assente/vuoto")
            if req['verb'] and not has(vb): probs.append(f"verb {vb!r} richiesto ma assente")
            if req['adjective'] and not has(adj): probs.append(f"adjective {adj!r} richiesto ma assente")
            if obj and not has(obj): probs.append(f"object {obj!r} assente")
            if not re.search(stop,r): probs.append("manca il terminatore")
            if len(r.split())>mw: probs.append(f"{len(r.split())} parole > max_response_words={mw}")
            if probs:
                bad+=1
                print(f"  L{L} step {sname}  {r!r}: " + "; ".join(probs))
print(("TUTTI I TARGET OK" if not bad else f"{bad} TARGET NON POSSONO OTTENERE +++"))

# ── One prompt, one gold ─────────────────────────────────────────────────────
# A prompt with two gold answers is contradictory supervision: whichever the
# model produces, the grader marks it wrong part of the time, and the level's
# exact match reads as a regression that never happened. It crept in twice --
# a generator mapping two items onto one prompt ('chi mangia la torta?' had
# four answers), and two levels asking the same question with different
# expected shapes ('cosa fa il cane?' at L3 with one verb, at L5 with two).
# Checked across pools AND the pairs harvested from sessions, because the
# harvest is the channel that reintroduced it.
import collections
gold = collections.defaultdict(lambda: collections.defaultdict(set))
# The gold-clash check always spans EVERY level, even when a single level was
# passed on the command line: a clash is a relation between two levels, so
# narrowing the sweep is how you get a clean report on a broken corpus.
for L in levels_on_disk():
    d = f'training_files/it/{L}'
    p = f'{d}/local_teacher.json'
    if os.path.exists(p):
        cfg = json.load(open(p))
        for sname, s in cfg.get('steps', {}).items():
            tmpl = s.get('prompt_template', '{prompt}')
            for t in s['targets']:
                if not isinstance(t, dict):
                    continue
                pr = tmpl.format(prompt=t.get('prompt', ''),
                                 target=t.get('prompt', ''))
                gold[pr.strip()][t.get('expected', '').strip()].add(f'pool L{L}{sname}')
    q = f'{d}/qa_pairs.jsonl'
    if os.path.exists(q):
        for line in open(q, encoding='utf-8'):
            line = line.strip()
            if not line:
                continue
            try:
                o = json.loads(line)
            except json.JSONDecodeError:
                continue
            gold[o.get('prompt', '').strip()][o.get('response', '').strip()].add(f'qa L{L}')

clash = {p: v for p, v in gold.items() if len(v) > 1}
for p, resps in sorted(clash.items()):
    print(f'  {p!r} ha {len(resps)} risposte gold:')
    for r, srcs in sorted(resps.items()):
        print(f'      {r!r}  [{", ".join(sorted(srcs))}]')
print(('OGNI PROMPT HA UN SOLO GOLD' if not clash
       else f'{len(clash)} PROMPT CON GOLD CONTRASTANTI '
            f'(correggi con scripts/fix_gold_conflicts.py)'))

# ── the three roles of bare_unknown_nouns ────────────────────────────────────
# The pool split only works if the roles are respected on disk. Each of these
# is a measurement that silently becomes meaningless when it is not:
#   probe    - taught anywhere at all, and the answer to 'did the honesty
#              relation generalise?' becomes 'we taught it';
#   reserve  - retracted, and the control that acquisition has not eroded
#              honesty is gone;
#   retracted- an admission left behind somewhere, and the prompt has two golds
#              under two shapes, which is the failure ask_forms exists for.
print()
role_bad = []
try:
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    from dynamic_model.retraction import retracted, find, is_admission
    lexicon = json.load(open('training_files/it/lexicon.json', encoding='utf-8'))
    bare = lexicon.get('bare_unknown_nouns', [])
    gone = set(retracted('it'))
    roles = collections.Counter(n.get('role', 'acquirable') for n in bare)

    for n in bare:
        role = n.get('role', 'acquirable')
        hit = find(n['w'], 'it')
        taught = sum(len(part['targets']) + len(part['pairs'])
                     for part in hit['levels'].values())
        if role == 'probe' and (taught or hit['other']):
            role_bad.append(f"'{n['w']}' ha role=probe ma compare in "
                            f"{taught + len(hit['other'])} punti del "
                            f"curriculum: la misura di generalizzazione è persa")
        if role == 'reserve' and n['w'] in gone:
            role_bad.append(f"'{n['w']}' ha role=reserve ma è stato ritirato: "
                            f"il controllo permanente è stato speso")
        if role == 'reserve' and not taught:
            role_bad.append(f"'{n['w']}' ha role=reserve ma nessun livello gli "
                            f"insegna 'non lo so'")
        if hit['other']:
            role_bad.append(f"'{n['w']}' è un bare_unknown ma ha "
                            f"{len(hit['other'])} gold che non sono ammissioni")
    for w in gone:
        hit = find(w, 'it')
        left = sum(len(part['targets']) + len(part['pairs'])
                   for part in hit['levels'].values())
        if left:
            role_bad.append(f"'{w}' è ritirato ma restano {left} ammissioni "
                            f"nel curriculum")
    for line in role_bad:
        print(f'  {line}')
    print(f"RUOLI bare_unknown: {dict(roles)}, ritirati {len(gone)} — "
          + ('ok' if not role_bad else f'{len(role_bad)} PROBLEMI'))
except Exception as e:                       # noqa: BLE001
    print(f'  ruoli non verificati: {e}')

sys.exit(1 if (bad or clash or role_bad) else 0)
