#!/usr/bin/env python3
"""Every target must be able to reach '+++' with its own gold answer,
otherwise the teacher loops on it forever: '+' is a soft positive that
resets the failure counter without advancing the success counter."""
import glob, json, re, sys, os

# Which curriculum to validate. The configs live per language under
# training_files/<lang>/, and this used to say 'it' in every path while
# advertising a lang parameter -- so `validate_teacher_configs.py 0` on an
# English tree silently validated the Italian one and reported it clean.
#
#   scripts/validate_teacher_configs.py                 # it, every level
#   scripts/validate_teacher_configs.py --lang en       # en, every level
#   scripts/validate_teacher_configs.py --lang en 0 1   # en, levels 0 and 1
LANG = os.environ.get('PHYSISML_LANG', 'it')
_argv = []
_next_lang = False
for a in sys.argv[1:]:
    if _next_lang:
        LANG = a; _next_lang = False; continue
    if a == '--lang':
        _next_lang = True
    elif a.startswith('--lang='):
        LANG = a.split('=', 1)[1]
    else:
        _argv.append(a)
print(f'language: {LANG}  (training_files/{LANG}/)')

bad=0
# The levels come from disk, not from a range. A hardcoded upper bound silently
# skips the levels most in need of checking -- it read range(0,13) while the
# autonomy loop was writing level 13, so the one config being generated by a
# machine instead of a human was the one nobody validated.
def levels_on_disk(lang=None):
    lang = lang or LANG
    out=[]
    for d in glob.glob(f'training_files/{lang}/*'):
        name=os.path.basename(d)
        if name.isdigit() and os.path.exists(f'{d}/local_teacher.json'):
            out.append(int(name))
    return sorted(out)

LEVELS = ([int(a) for a in _argv if a.isdigit()] or levels_on_disk())
for L in LEVELS:
    p=f'training_files/{LANG}/{L}/local_teacher.json'
    if not os.path.exists(p): continue
    cfg=json.load(open(p))
    stop=cfg.get('evaluation',{}).get('has_terminator_pattern','[.!?]')
    for sname,s in cfg.get('steps',{}).items():
        req={k:s.get(f'require_{k}',False) for k in ('article','verb','adjective')}
        mw=s.get('max_response_words',6)
        for t in s['targets']:
            if not isinstance(t,dict):
                continue
            r=t.get('expected','')
            noun=t.get('noun',''); art=t.get('article',''); vb=t.get('verb',''); adj=t.get('adjective',''); obj=t.get('object','')
            comp=re.sub(r'\s+','',r)
            def has(w): return True if not w else (bool(re.search(r'\b'+re.escape(w)+r'\b',r)) or (len(w)>=4 and w in comp))
            probs=[]
            if not has(noun): probs.append(f"noun {noun!r} missing")
            if req['article'] and not (art and art in r.split()[:5]): probs.append(f"article {art!r} required but missing/empty")
            if req['verb'] and not has(vb): probs.append(f"verb {vb!r} required but missing")
            if req['adjective'] and not has(adj): probs.append(f"adjective {adj!r} required but missing")
            if obj and not has(obj): probs.append(f"object {obj!r} missing")
            if not re.search(stop,r): probs.append("terminator missing")
            if len(r.split())>mw: probs.append(f"{len(r.split())} words > max_response_words={mw}")
            if probs:
                bad+=1
                print(f"  L{L} step {sname}  {r!r}: " + "; ".join(probs))
print(("ALL TARGETS OK" if not bad else f"{bad} TARGETS CANNOT REACH +++"))

# ── One prompt, one gold ─────────────────────────────────────────────────────
# A prompt with two gold answers is contradictory supervision: whichever the
# model produces, the grader marks it wrong part of the time, and the level's
# exact match reads as a regression that never happened. It crept in twice --
# a generator mapping two items onto one prompt ('chi mangia la torta?' had
# four answers), and two levels asking the same question with different
# expected shapes ('cosa fa il cane?' at L3 with one verb, at L5 with two).
# Checked across pools AND the pairs harvested from sessions, because the
# harvest is the channel that reintroduced it.
import collections
gold = collections.defaultdict(lambda: collections.defaultdict(set))
# The gold-clash check always spans EVERY level, even when a single level was
# passed on the command line: a clash is a relation between two levels, so
# narrowing the sweep is how you get a clean report on a broken corpus.
for L in levels_on_disk():
    d = f'training_files/{LANG}/{L}'
    p = f'{d}/local_teacher.json'
    if os.path.exists(p):
        cfg = json.load(open(p))
        for sname, s in cfg.get('steps', {}).items():
            tmpl = s.get('prompt_template', '{prompt}')
            for t in s['targets']:
                if not isinstance(t, dict):
                    continue
                pr = tmpl.format(prompt=t.get('prompt', ''),
                                 target=t.get('prompt', ''))
                gold[pr.strip()][t.get('expected', '').strip()].add(f'pool L{L}{sname}')
    q = f'{d}/qa_pairs.jsonl'
    if os.path.exists(q):
        for line in open(q, encoding='utf-8'):
            line = line.strip()
            if not line:
                continue
            try:
                o = json.loads(line)
            except json.JSONDecodeError:
                continue
            gold[o.get('prompt', '').strip()][o.get('response', '').strip()].add(f'qa L{L}')

clash = {p: v for p, v in gold.items() if len(v) > 1}
for p, resps in sorted(clash.items()):
    print(f'  {p!r} has {len(resps)} gold answers:')
    for r, srcs in sorted(resps.items()):
        print(f'      {r!r}  [{", ".join(sorted(srcs))}]')
print(('EVERY PROMPT HAS A SINGLE GOLD' if not clash
       else f'{len(clash)} PROMPTS WITH CLASHING GOLDS '
            f'(fix them with scripts/fix_gold_conflicts.py)'))

# ── the three roles of bare_unknown_nouns ────────────────────────────────────
# The pool split only works if the roles are respected on disk. Each of these
# is a measurement that silently becomes meaningless when it is not:
#   probe    - taught anywhere at all, and the answer to 'did the honesty
#              relation generalise?' becomes 'we taught it';
#   reserve  - retracted, and the control that acquisition has not eroded
#              honesty is gone;
#   retracted- an admission left behind somewhere, and the prompt has two golds
#              under two shapes, which is the failure ask_forms exists for.
print()
role_bad = []
try:
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    from dynamic_model.retraction import retracted, find
    lexicon = json.load(open(f'training_files/{LANG}/lexicon.json', encoding='utf-8'))
    bare = lexicon.get('bare_unknown_nouns', [])
    gone = set(retracted(LANG))
    roles = collections.Counter(n.get('role', 'acquirable') for n in bare)

    for n in bare:
        role = n.get('role', 'acquirable')
        hit = find(n['w'], LANG)
        taught = sum(len(part['targets']) + len(part['pairs'])
                     for part in hit['levels'].values())
        if role == 'probe' and (taught or hit['other']):
            role_bad.append(f"'{n['w']}' has role=probe but shows up at "
                            f"{taught + len(hit['other'])} points of the "
                            f"curriculum: the generalisation measure is lost")
        if role == 'reserve' and n['w'] in gone:
            role_bad.append(f"'{n['w']}' has role=reserve but was retracted: "
                            f"the permanent control has been spent")
        if role == 'reserve' and not taught:
            role_bad.append(f"'{n['w']}' has role=reserve but no level teaches "
                            f"it 'non lo so'")
        # A retracted word is SUPPOSED to carry class golds now: retraction is
        # what acquisition does to an admission, and the ledger is the record
        # of that transition. Flagging its new golds would flag every
        # successful acquisition. The residue check below still catches any
        # admission left behind for the same word.
        if hit['other'] and n['w'] not in gone:
            role_bad.append(f"'{n['w']}' is a bare_unknown but has "
                            f"{len(hit['other'])} golds that do not treat it "
                            f"as unknown")
    for w in gone:
        hit = find(w, LANG)
        left = sum(len(part['targets']) + len(part['pairs'])
                   for part in hit['levels'].values())
        if left:
            role_bad.append(f"'{w}' is retracted but {left} admissions are "
                            f"left in the curriculum")
        # Retraction is only legitimate as half of an acquisition: the ledger
        # word must carry at least one replacement gold somewhere, or the
        # curriculum simply lost it. The first real run left ten nouns in
        # exactly this state (cap checked after the retraction, 2026-09-03).
        if not hit['other']:
            role_bad.append(f"'{w}' is retracted but no gold replaces it: "
                            f"neither admission nor class, a silent hole")
    for line in role_bad:
        print(f'  {line}')
    print(f"bare_unknown ROLES: {dict(roles)}, retracted {len(gone)} — "
          + ('ok' if not role_bad else f'{len(role_bad)} PROBLEMS'))
except Exception as e:                       # noqa: BLE001
    print(f'  roles not verified: {e}')

sys.exit(1 if (bad or clash or role_bad) else 0)
